name: build
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
        MRUBY_CONDFIG: ../.github_actions_build_config.rb
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: | 
          sudo apt-get -qq update
          sudo apt-get -qq install rake bison git gperf libusb-1.0
      - name: Clone mruby
        run: git clone https://github.com/mruby/mruby.git
      - name: Test
        run: |
          cd mruby
          rake
